export const GET_HOME_PRODUCTS = "GET_HOME_PRODUCTS";
export const GET_CATEGORY_PRODUCTS = "GET_CATEGORY_PRODUCTS";
export const GET_SEARCH_PRODUCTS = "GET_SEARCH_PRODUCTS";
export const GET_SINGLE_PRODUCT = "GET_SINGLE_PRODUCT";

export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";
export const LOAD_USER = "LOAD_USER";
export const FORGOT_PASSWORD = "FORGOT_PASSWORD";
export const REGISTER = "REGISTER";
export const RESET_PASSWORD = "RESET_PASSWORD";
export const GET_FAVOURITE = "GET_FAVOURITE";
export const ADD_FAVOURITE = "ADD_FAVOURITE";
export const REMOVE_FAVOURITE = "REMOVE_FAVOURITE";

export const GET_LOCATION = "GET_LOCATION";
export const ADD_LOCATION = "ADD_LOCATION";
export const DELETE_LOCATION = "DELETE_LOCATION";

export const REMOVE_ITEM_FROM_CART = "REMOVE_ITEM_FROM_CART";
export const MULTIPLE_UPDATE_CART = "MULTIPLE_UPDATE_CART";
export const UPDATE_CART = "UPDATE_CART";
export const GET_CART = "GET_CART";
export const ADD_TO_CART = "ADD_TO_CART";
export const MULTIPLE_ADD_TO_CART = "MULTIPLE_ADD_TO_CART";

export const GET_ORDERS = "GET_ORDERS";
export const CREATE_ORDER = "CREATE_ORDER";
export const GET_SINGLE_ORDERS = "GET_SINGLE_ORDERS";
export const POST_REVIEW = "POST_REVIEW";

export const GET_COUPON = "GET_COUPON";
