export const primaryColor = "#fe7502";
export const categories = [
  "Breakfast",
  "Favourites!",
  "Healthy",
  "Kebab",
  "Dessert",
  "Baked",
  "Cakes",
  "Biryani",
  "Curry",
  "Platter",
  "Dawat",
  "Achar & Sauce",
];
export const categoriesImages = [
  // { category: "Breakfast", uri: require("../assets/Breakfast.jpg") },
  { category: "Favourites!", uri: require("../assets/Favourites!.jpg") },
  { category: "Healthy", uri: require("../assets/Healthy.jpg") },
  { category: "Kebab", uri: require("../assets/Kebab.jpg") },
  { category: "Dessert", uri: require("../assets/Dessert.jpg") },
  { category: "Baked", uri: require("../assets/Baked.jpg") },
  { category: "Cakes", uri: require("../assets/Cakes.jpg") },
  { category: "Biryani", uri: require("../assets/Biryani.jpg") },
  { category: "Curry", uri: require("../assets/Curry.jpg") },
  // { category: "Platter", uri: require("../assets/Platter.jpg") },
  // { category: "Dawat", uri: require("../assets/Dawat.jpg") },
  { category: "Achar & Sauce", uri: require("../assets/Achar.jpg") },
];

export const tags = [
  "Afghani",
  "American",
  "Appetizer",
  "Arabic",
  "Argentinian",
  "Asian",
  "Baby Food",
  "Bakery",
  "Bangali",
  "Bangali Chinese",
  "Brazilian",
  "British",
  "Burmese",
  "Caribbean",
  "Chatgaya",
  "Chinese",
  "Condiment",
  "Continental",
  "CookupsFit",
  "CookupsX",
  "Dessert",
  "Dhakaiya",
  "Drink",
  "Eastern European",
  "Ethiopian",
  "European (Other)",
  "Filipino",
  "French",
  "Fusion",
  "German",
  "Greek",
  "Growups",
  "Healthy",
  "Indian",
  "Indonesian",
  "Italian",
  "Japanese",
  "Keto-Friendly",
  "Kids",
  "Korean",
  "Lebanese",
  "Lo-carb",
  "Malay/Indonesian",
  "Malaysian",
  "Maldivian",
  "Mediterranean",
  "Mexican",
  "Middle-Eastern",
  "Mongolian",
  "Mughlai",
  "Nepalese",
  "North African",
  "Other",
  "Pakistani",
  "Paleo-Friendly",
  "Pet Food",
  "Puerto Rican",
  "Punjabi",
  "Russian",
  "Salad",
  "Shahi",
  "Singaporean",
  "Snack",
  "Snacks",
  "South American",
  "South Asian",
  "South East Asian",
  "South Indian",
  "Spanish",
  "Sri Lankan",
  "Swedish",
  "Sylheti",
  "Thai",
  "Turkish",
  "Vegan",
  "Vegetarian",
  "Vietnamese",
  "West Bengali",
  "Whole 30",
];

export const DELIVERY_CHARGE = 100;
export const TAX_RATE = 0.0015;

export const TIMES = [
  "08:30 AM - 09:30 AM",
  "09:30 AM - 10:30 AM",
  "10:30 AM - 11:30 AM",
  "11:30 AM - 12:30 AM",
  "12:30 AM - 01:30 AM",
  "01:30 PM - 02:30 PM",
  "02:30 PM - 03:30 PM",
  "03:30 PM - 04:30 PM",
  "04:30 PM - 04:30 PM",
  "04:30 PM - 05:30 PM",
  "05:30 PM - 06:30 PM",
  "06:30 PM - 07:30 PM",
  "07:30 PM - 08:30 PM",
  "08:30 PM - 09:30 PM",
];

export const AREAS = [
  "Adabar",
  "Badda",
  "Bangsal",
  "Cantonment",
  "Chowkbazar",
  "Darus Salam",
  "Demra",
  "Dhakshinkhan",
  "Dhanmondi",
  "Gendaria",
  "Gulshan",
  "Hazaribagh",
  "Jatrabari",
  "Kadamtali",
  "Kafrul",
  "Kalabagan",
  "Kamrangirchar",
  "Khilgaon",
  "Khilkhet",
  "Lalbagh",
  "Mirpur ",
  "Mohammadpur",
  "Motijheel",
  "New Market",
  "Pallabi",
  "Paltan",
  "Panthapath",
  "Ramna",
  "Rampura",
  "Sabujbagh",
  "Shah Ali",
  "Shahbag",
  "Sher-e-Bangla Nagar",
  "Shyampur",
  "Sutrapur",
  "Tejgaon",
  "Turag",
  "Uttara",
  "Uttar Khan",
  "Vatara",
  "Wari",
];
